# Generated by Django 4.2.11 on 2025-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='bigpic/')),
            ],
        ),
    ]
