# Generated by Django 4.2.11 on 2025-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('processing', 'В обработке'), ('completed', 'Доставлено'), ('cancelled', 'Отменено')], default='pending', max_length=20),
        ),
    ]
