# Generated by Django 4.2.11 on 2025-04-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_address_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('warning', 'В ожидании'), ('warning', 'В обработке'), ('success', 'Доставлено'), ('danger', 'Отменено')], default='pending', max_length=20),
        ),
    ]
